<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="universities" nsURI="https://universities" nsPrefix="universities">
  <eClassifiers xsi:type="ecore:EClass" name="Student">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="student_nr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="University">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="faculties" upperBound="-1"
        eType="#//Faculty"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Faculty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//Course"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="professors" upperBound="-1"
        eType="#//Professor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Professor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edition_nr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="professors" upperBound="-1"
        eType="#//Professor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="students" upperBound="-1"
        eType="#//Student"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editions" upperBound="-1"
        eType="#//Edition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Grade">
    <eStructuralFeatures xsi:type="ecore:EReference" name="student" lowerBound="1"
        eType="#//Student"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edition" lowerBound="1"
        eType="#//Edition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="grade" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
  </eClassifiers>
</ecore:EPackage>
